### ISSUE TITLE
Add support for macos 11 arch64

### ISSUE THREAD

**Issue by yabirgb** [crate-py/rpds#11]
We had an issue with our CI since we depende on jsonchema that recently introduced rpds as dependency. Would be possible to add a wheel for macos 11 arch64? 

https://github.com/rotki/rotki/actions/runs/5485326087/jobs/9994007923#step:14:630

Currently there are macos 10 x86_64 and macos 11 arm64 but I'm not aware if there is a restriction for the 2 combinations missing

**Comment by Julian** [comment]
If you have an idea of what to tweak that'd be appreciated. Otherwise yeah if this is doable in GH Actions I'll take a look at some point.

**Comment by Julian** [comment]
Do you have the output of a run which failed here, and can you include `pip debug --verbose` from a machine which failed?

I'm looking again at this and I'm not sure anything is wrong here -- the wheels are *minimum* macOS versions AFAIK -- maturin it looks like is using `MACOS_DEPLOYMENT_TARGET` minimums of `10.7` for x86_64 and `11` for arm (and I assume the latter because no macOS machines existed previously to Big Sur).

**Comment by Julian** [comment]
Closing given the above but someone chime in if indeed you see something concretely missing.
