### ISSUE TITLE
Upload wheels for 3.12 on Windows

### ISSUE THREAD

**Issue by KotlinIsland** [crate-py/rpds#26]

**Comment by Julian** [comment]
I gave this a shot in a few commits, but maturin and/or GHA doesn't seem happy finding Py312 on Windows.

PR welcome from someone interested.

**Comment by here-abarany** [comment]
It looks like using `python-version: 3.x` for `setup-python` is installing Python 3.11.5 rather than 3.12. My guess is if you set `python-version: 3.12` explicitly then it should work. Based on [this issue in setup-python](https://github.com/actions/setup-python/issues/736), the reason why it's picking up the older version may be because the newer version isn't cached yet.

**Comment by Julian** [comment]
I've tried ([in one of the commits](https://github.com/crate-py/rpds/commit/537fae2ce5fc2a0dd6c9a9b013cb005b322532a8)) explicitly installing 3.12 as well, and that didn't make the cache find it either on Windows.

**Comment by here-abarany** [comment]
It looks like the error in that build was due to not finding PyPy 3.8. Maybe worth trying again with explicitly installing 3.12 but leaving out the PyPy versions?

**Comment by here-abarany** [comment]
I have submitted PR #27 to manually install just the cpython versions and that appears to work.
