### ISSUE TITLE
Add support for termux118

### ISSUE THREAD

**Issue by gigberg** [crate-py/rpds#30]
This package is now a dependency of [jsonschema v4.18.0](https://github.com/python-jsonschema/jsonschema/blob/main/CHANGELOG.rst#v4180),, and of jupyter notebook==7.

It takes time to compile rpds_py for source code,,which make problem when pip install notebook=7 in [termux platform](https://github.com/termux/termux-app).
[https://www.reddit.com/r/termux/comments/157mw29/comment/k6ibrlf/?utm_source=share&utm_medium=web2x&context=3](https://www.reddit.com/r/termux/comments/157mw29/comment/k6ibrlf/?utm_source=share&utm_medium=web2x&context=3)

Would be possible to add a wheel for termux on Android in [the repository's Github Action](https://github.com/crate-py/rpds/blob/main/.github/workflows/CI.yml)?

May this should be the problem of maturin..... instead of rpds......

**Comment by Julian** [comment]
I'd love to, but as far as I know, this still isn't possible. Specifically (and I'm being lazy and not looking for the issues to link you to, but you likely can find them yourself) Termux does not support any wheel ABI tags which PyPI allows uploading. You can check what it wants by running `pip debug --verbose` in your Termux environment, where you'll see that Termux is only supporting `linux_aarch64` tags, which are nonstandard, and not supported by PyPI (because they don't work on most or even many linuxes in a standard way). The standard way is manylinux (or muslinux) wheels which are already supported.

My recommendation here is to either make use of one of a few "termux wheels" repositories which *do* allow uploading these nonstandard wheels, or to help discuss upstream what would be needed to standardize things so that Termux uses something PyPI can support uploads for (I'm not sure what the status of getting manylinux to work on Termux for example is).

Going to close given the above, but happy to hear follow-ups or to revisit when things improve upstream, though it's likely that when that happens things will work out of the box here.
