### ISSUE TITLE
platform=linux_x86_64  not working

### ISSUE THREAD

**Issue by itymanuel** [crate-py/rpds#69]
Tried:
pip install -r ../requirements.txt --target=./python --platform=linux_x86_64 --no-deps

I got this error:
Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]

      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/

Is it possible to have it prebuilt for linux_x86_64 ?

Thanks!

**Comment by Julian** [comment]
Hey! `linux_x86_64` doesn't really exist / isn't supported on PyPI (see https://peps.python.org/pep-0513/#rationale ) -- manylinux is what is used for Linux builds and we already publish them! See e.g. #19 or #30 though if you're on one of those platforms -- in which case we still can't publish wheels for them to PyPI (because the wheel tags do not really exist, they're nonstandard) but if you're on those platforms you may be interested in helping upstream to standardize them.
